git fetch
git stage .
RAND=`date +%S:%N`
git commit -m "Autogenerated commit: $RAND" > git_log
read -p "Press read " ip
git pull
git push
read -p "Press read " ip
python3 test.py
read -p "Press [Enter] key" ip